Repository Genie-Uss/genieus, pull requests merged in 2025-05, with the labels that each got.

#107 [Feat] 재고 이벤트 히스토리 배치 처리 시스템 구현
  product-service/build.gradle
  product-service/src/main/java/shop/genieus/product/domain/model/entity/StockHistory.java
  product-service/src/main/java/shop/genieus/product/global/config/RedisConfig.java
  product-service/src/main/java/shop/genieus/product/infrastructure/batch/config/StockHistoryBatchJobConfig.java
  product-service/src/main/java/shop/genieus/product/infrastructure/batch/config/StockHistoryBatchSchedulerConfig.java
  product-service/src/main/java/shop/genieus/product/infrastructure/batch/context/StockEventProcessingContext.java
  product-service/src/main/java/shop/genieus/product/infrastructure/batch/mapper/StockEventMapper.java
  product-service/src/main/java/shop/genieus/product/infrastructure/batch/repository/StockEventRedisRepository.java
  product-service/src/main/java/shop/genieus/product/infrastructure/batch/repository/model/StockEventBatchResult.java
  product-service/src/main/java/shop/genieus/product/infrastructure/batch/service/StockEventProcessingService.java
  product-service/src/main/java/shop/genieus/product/infrastructure/batch/service/StockEventQueueReader.java
  product-service/src/main/java/shop/genieus/product/infrastructure/batch/service/StockHistoryBatchWriter.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/repository/ProductRedisRepository.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/util/ProductLuaScriptProvider.java
  product-service/src/main/resources/application-dev.yml
  product-service/src/main/resources/application.yml
  product-service/src/main/resources/batch-dev.yml
  product-service/src/main/resources/batch-local.yml
  product-service/src/main/resources/docker-database.yml
  product-service/src/main/resources/redis-key.yml
  product-service/src/main/resources/redis/multi-get-hash-keys.lua
  product-service/src/main/resources/redis/order-completed.lua
  product-service/src/main/resources/redis/restore-total-stock-script.lua
Labels: ❤️‍🔥 Feat

#108 [Fix] 주문 트랜잭션관련 수정
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderCommandService.java
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderTransactionalSupport.java
  order-service/src/main/java/shop/genieus/order/application/in/event/OrderInternalEventService.java
  order-service/src/main/java/shop/genieus/order/application/in/scheduler/OrderSchedulerService.java
  order-service/src/main/java/shop/genieus/order/application/out/event/OrderInternalEventPort.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/producer/OrderKafkaProducer.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/internal/OrderInternalEventAdapter.java
  order-service/src/main/java/shop/genieus/order/presentation/event/internal/OrderInternalEventListener.java
  order-service/src/main/resources/application-dev.yml
Labels: ⚒️ Fix

#110 [Chore] ci-cd develop에서 main으로 변경
  .github/workflows/main-ci-cd.yml
Labels: 🕹️ Chore
