Repository Genie-Uss/genieus, pull requests merged in 2025-04, with the labels that each got.

#8 [Feat] User Entity 및 값 객체 설계
  user-service/build.gradle
  user-service/src/main/java/shop/genieus/user/application/out/support/encoder/PasswordEncryptionPort.java
  user-service/src/main/java/shop/genieus/user/domain/model/entity/BaseEntity.java
  user-service/src/main/java/shop/genieus/user/domain/model/entity/User.java
  user-service/src/main/java/shop/genieus/user/domain/model/service/PasswordEncryptionService.java
  user-service/src/main/java/shop/genieus/user/domain/model/vo/Address.java
  user-service/src/main/java/shop/genieus/user/domain/model/vo/BirthInfo.java
  user-service/src/main/java/shop/genieus/user/domain/model/vo/Email.java
  user-service/src/main/java/shop/genieus/user/domain/model/vo/Gender.java
  user-service/src/main/java/shop/genieus/user/domain/model/vo/Name.java
  user-service/src/main/java/shop/genieus/user/domain/model/vo/Password.java
  user-service/src/main/java/shop/genieus/user/domain/model/vo/PhoneNumber.java
  user-service/src/main/java/shop/genieus/user/domain/model/vo/Role.java
  user-service/src/main/java/shop/genieus/user/domain/model/vo/RoleType.java
  user-service/src/main/java/shop/genieus/user/global/config/JpaConfig.java
  user-service/src/main/java/shop/genieus/user/global/config/PasswordSecurityConfig.java
  user-service/src/main/java/shop/genieus/user/infrastructure/support/encoder/BCryptPasswordEncryptionAdapter.java
Labels: ❤️‍🔥 Feat

#13 [Feat] 인증 서비스 JWT 기반 로그인 구현
  auth-service/build.gradle
  auth-service/src/main/java/shop/genieus/auth/application/in/command/AuthenticationCommandService.java
  auth-service/src/main/java/shop/genieus/auth/application/in/command/dto/LoginCommand.java
  auth-service/src/main/java/shop/genieus/auth/application/out/persistence/AuthPersistencePort.java
  auth-service/src/main/java/shop/genieus/auth/application/out/support/id/IdGeneratorPort.java
  auth-service/src/main/java/shop/genieus/auth/application/out/support/token/AuthTokenPort.java
  auth-service/src/main/java/shop/genieus/auth/domain/model/entity/User.java
  auth-service/src/main/java/shop/genieus/auth/domain/model/vo/Password.java
  auth-service/src/main/java/shop/genieus/auth/global/config/JwtConfig.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/persistence/AuthPersistenceAdapter.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/persistence/repository/TokenRedisRepository.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/persistence/repository/UserJpaRepository.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/persistence/util/LuaScriptProvider.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/support/id/UuidGeneratorAdapter.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/support/token/AuthJwtAdapter.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/support/token/util/AbstractJwtSupport.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/support/token/util/JwtProvider.java
  auth-service/src/main/java/shop/genieus/auth/presentation/rest/controller/AuthController.java
  auth-service/src/main/java/shop/genieus/auth/presentation/rest/dto/AuthApiResponse.java
  auth-service/src/main/java/shop/genieus/auth/presentation/rest/dto/request/LoginRequest.java
  auth-service/src/main/java/shop/genieus/auth/presentation/rest/dto/response/LoginResponse.java
  auth-service/src/main/resources/application-local.yml
  auth-service/src/main/resources/redis/save-refresh-token.lua
  auth-service/src/main/resources/sql/create_auth_user.sql
Labels: ❤️‍🔥 Feat

#15 [Feat] auth service 로그아웃 기능 구현
  auth-service/src/main/java/shop/genieus/auth/application/in/command/AuthenticationCommandService.java
  auth-service/src/main/java/shop/genieus/auth/application/in/command/dto/LogoutCommand.java
  auth-service/src/main/java/shop/genieus/auth/application/out/persistence/AuthPersistencePort.java
  auth-service/src/main/java/shop/genieus/auth/application/out/support/token/AuthTokenPort.java
  auth-service/src/main/java/shop/genieus/auth/domain/model/TokenValidationResult.java
  auth-service/src/main/java/shop/genieus/auth/domain/model/entity/User.java
  auth-service/src/main/java/shop/genieus/auth/domain/model/vo/JwtAssociation.java
  auth-service/src/main/java/shop/genieus/auth/global/exception/TokenExpiredException.java
  auth-service/src/main/java/shop/genieus/auth/global/exception/TokenParsingException.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/persistence/AuthPersistenceAdapter.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/persistence/repository/TokenRedisRepository.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/support/token/AuthJwtAdapter.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/support/token/util/JwtValidator.java
  auth-service/src/main/java/shop/genieus/auth/presentation/rest/controller/AuthController.java
  auth-service/src/main/java/shop/genieus/auth/presentation/rest/dto/request/LogoutRequest.java
  auth-service/src/main/java/shop/genieus/auth/presentation/rest/dto/response/LogoutResponse.java
Labels: ❤️‍🔥 Feat

#22 [Feat,Chore] 쿠폰 엔티티 설계 및 쿠폰 생성 API 구현
  coupon-service/.gitignore
  coupon-service/build.gradle
  coupon-service/src/main/java/shop/genieus/coupon/CouponServiceApplication.java
  coupon-service/src/main/java/shop/genieus/coupon/application/in/command/CouponCommandService.java
  coupon-service/src/main/java/shop/genieus/coupon/application/in/command/dto/CreateCouponCommand.java
  coupon-service/src/main/java/shop/genieus/coupon/application/out/persistence/CouponCommandPort.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/entity/BaseEntity.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/entity/Coupon.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/entity/CouponUser.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/vo/CouponDiscountRate.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/vo/CouponEndDate.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/vo/CouponExpiredDate.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/vo/CouponStartDate.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/vo/CouponStatus.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/vo/CouponUseStatus.java
  coupon-service/src/main/java/shop/genieus/coupon/global/config/CommonLibConfig.java
  coupon-service/src/main/java/shop/genieus/coupon/global/config/JpaConfig.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/CouponCommandAdaptor.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponJpaRepository.java
  coupon-service/src/main/java/shop/genieus/coupon/presentation/rest/controller/CouponController.java
  coupon-service/src/main/java/shop/genieus/coupon/presentation/rest/dto/request/CreateCouponRequest.java
  coupon-service/src/main/java/shop/genieus/coupon/presentation/rest/dto/response/CouponResponse.java
Labels: 🕹️ Chore, ❤️‍🔥 Feat

#25 [Feat] API 게이트웨이 설계 및 인증 연결 구현
  api-gateway/src/main/java/shop/genieus/gateway/client/AuthServiceClient.java
  api-gateway/src/main/java/shop/genieus/gateway/client/dto/AuthClientRequest.java
  api-gateway/src/main/java/shop/genieus/gateway/client/dto/AuthClientResponse.java
  api-gateway/src/main/java/shop/genieus/gateway/config/GatewayConfig.java
  api-gateway/src/main/java/shop/genieus/gateway/config/GlobalFilterConfig.java
  api-gateway/src/main/java/shop/genieus/gateway/config/WebClientConfig.java
  api-gateway/src/main/java/shop/genieus/gateway/config/WebFilterConfig.java
  api-gateway/src/main/java/shop/genieus/gateway/constants/AppConstants.java
  api-gateway/src/main/java/shop/genieus/gateway/filter/auth/AuthenticationFilter.java
  api-gateway/src/main/java/shop/genieus/gateway/filter/auth/AuthenticationGatewayFilterFactory.java
  api-gateway/src/main/java/shop/genieus/gateway/filter/auth/TokenExtractorFilter.java
  api-gateway/src/main/java/shop/genieus/gateway/filter/auth/TokenExtractorGatewayFilterFactory.java
  api-gateway/src/main/java/shop/genieus/gateway/filter/logging/RequestLoggingFilter.java
  api-gateway/src/main/java/shop/genieus/gateway/filter/logging/ResponseLoggingFilter.java
  api-gateway/src/main/resources/application-local.yml
  api-gateway/src/main/resources/local-route.yml
Labels: ❤️‍🔥 Feat

#24 [Feat,Chore] 주문 엔티티 및 주문-결제 프로세스 구현
  order-service/.gitignore
  order-service/build.gradle
  order-service/src/main/java/shop/genieus/order/OrderServiceApplication.java
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderCommandService.java
  order-service/src/main/java/shop/genieus/order/application/in/command/dto/CreateOrderCommand.java
  order-service/src/main/java/shop/genieus/order/application/in/command/dto/PaymentCommand.java
  order-service/src/main/java/shop/genieus/order/application/out/client/OrderClientPort.java
  order-service/src/main/java/shop/genieus/order/application/out/persistence/OrderCommandPort.java
  order-service/src/main/java/shop/genieus/order/application/out/util/OrderTimePort.java
  order-service/src/main/java/shop/genieus/order/domain/model/assembler/CreateOrderAssembler.java
  order-service/src/main/java/shop/genieus/order/domain/model/assembler/OrderProductAssembler.java
  order-service/src/main/java/shop/genieus/order/domain/model/entity/BaseEntity.java
  order-service/src/main/java/shop/genieus/order/domain/model/entity/Order.java
  order-service/src/main/java/shop/genieus/order/domain/model/entity/OrderProduct.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/Coupon.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/OrderPrice.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/OrderStatus.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/PaymentMethod.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/Phone.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/Product.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/PromotionProduct.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/Receiver.java
  order-service/src/main/java/shop/genieus/order/domain/service/OrderPriceCalculator.java
  order-service/src/main/java/shop/genieus/order/global/config/ClockConfig.java
  order-service/src/main/java/shop/genieus/order/global/config/FeignConfig.java
  order-service/src/main/java/shop/genieus/order/global/config/JpaConfig.java
  order-service/src/main/java/shop/genieus/order/global/exception/CustomBadRequestException.java
  order-service/src/main/java/shop/genieus/order/global/exception/CustomForbiddenException.java
  order-service/src/main/java/shop/genieus/order/global/exception/CustomNotFoundException.java
  order-service/src/main/java/shop/genieus/order/global/exception/CustomServiceUnavailableException.java
  order-service/src/main/java/shop/genieus/order/global/exception/ErrorCode.java
  order-service/src/main/java/shop/genieus/order/global/handler/GlobalExceptionHandler.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/OrderClientAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/feign/CouponFeignClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/feign/ProductFeignClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/feign/PromotionFeignClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/mapper/OrderClientMapper.java
  order-service/src/main/java/shop/genieus/order/infrastructure/persistence/OrderCommandAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/persistence/repository/OrderJpaRepository.java
  order-service/src/main/java/shop/genieus/order/infrastructure/time/OrderTimeAdapter.java
  order-service/src/main/java/shop/genieus/order/presentation/rest/controller/OrderController.java
  order-service/src/main/java/shop/genieus/order/presentation/rest/dto/request/CreateOrderRequest.java
  order-service/src/main/java/shop/genieus/order/presentation/rest/dto/request/PaymentRequest.java
  order-service/src/main/java/shop/genieus/order/presentation/rest/dto/response/CreateOrderResponse.java
  order-service/src/main/java/shop/genieus/order/presentation/rest/dto/response/PaymentResponse.java
  order-service/src/main/resources/application-local.yml
  order-service/src/test/java/shop/genieus/order/OrderServiceApplicationTests.java
Labels: 🕹️ Chore, ❤️‍🔥 Feat

#30 [Refactor] User, Auth, Gateway 리팩토링
  api-gateway/src/main/resources/local-route.yml
  auth-service/.gitignore
  auth-service/build.gradle
  auth-service/src/main/java/shop/genieus/auth/AuthServiceApplication.java
  auth-service/src/main/java/shop/genieus/auth/application/in/command/AuthenticationCommandService.java
  auth-service/src/main/java/shop/genieus/auth/application/in/command/PassportCommandService.java
  auth-service/src/main/java/shop/genieus/auth/application/out/persistence/AuthCommandPort.java
  auth-service/src/main/java/shop/genieus/auth/domain/model/Passport.java
  auth-service/src/main/java/shop/genieus/auth/domain/model/entity/User.java
  auth-service/src/main/java/shop/genieus/auth/domain/model/vo/Email.java
  auth-service/src/main/java/shop/genieus/auth/domain/model/vo/Role.java
  auth-service/src/main/java/shop/genieus/auth/global/common/AbstractEmail.java
  auth-service/src/main/java/shop/genieus/auth/global/common/AbstractRole.java
  auth-service/src/main/java/shop/genieus/auth/global/common/AuthClientResponse.java
  auth-service/src/main/java/shop/genieus/auth/global/common/GenieusPasswordEncoder.java
  auth-service/src/main/java/shop/genieus/auth/global/common/RoleType.java
  auth-service/src/main/java/shop/genieus/auth/global/config/PassportEncodingConfig.java
  auth-service/src/main/java/shop/genieus/auth/global/config/PasswordSecurityConfig.java
  auth-service/src/main/java/shop/genieus/auth/global/exception/AuthException.java
  auth-service/src/main/java/shop/genieus/auth/global/exception/TokenExpiredException.java
  auth-service/src/main/java/shop/genieus/auth/global/exception/TokenParsingException.java
  auth-service/src/main/java/shop/genieus/auth/global/handler/GlobalExceptionHandler.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/persistence/AuthCommandAdapter.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/support/encoder/BCryptPasswordEncryptionAdapter.java
  auth-service/src/main/java/shop/genieus/auth/infrastructure/support/encoder/Base64PassportEncodingAdapter.java
  auth-service/src/main/java/shop/genieus/auth/presentation/rest/controller/AuthInternalController.java
  auth-service/src/main/java/shop/genieus/auth/presentation/rest/dto/request/AuthClientRequest.java
  user-service/.gitignore
  user-service/build.gradle
  user-service/src/main/java/shop/genieus/user/UserServiceApplication.java
  user-service/src/main/java/shop/genieus/user/domain/model/entity/User.java
  user-service/src/main/java/shop/genieus/user/domain/model/vo/Role.java
  user-service/src/main/java/shop/genieus/user/global/exception/UserException.java
  user-service/src/main/java/shop/genieus/user/global/handler/GlobalExceptionHandler.java
Labels: ❤️‍🔥 Feat

#32 [Feat] Product: 상품 엔티티 설계 및 생성 로직 추가
  product-service/build.gradle
  product-service/src/main/java/shop/genieus/product/application/in/command/ProductCommandService.java
  product-service/src/main/java/shop/genieus/product/application/in/command/dto/CreateProductCommand.java
  product-service/src/main/java/shop/genieus/product/application/out/persistence/ProductCommandPort.java
  product-service/src/main/java/shop/genieus/product/domain/model/entity/BaseEntity.java
  product-service/src/main/java/shop/genieus/product/domain/model/entity/Product.java
  product-service/src/main/java/shop/genieus/product/domain/model/vo/ProductPrice.java
  product-service/src/main/java/shop/genieus/product/domain/model/vo/ProductStatus.java
  product-service/src/main/java/shop/genieus/product/global/common/auditor/AuditorAwareImpl.java
  product-service/src/main/java/shop/genieus/product/global/config/CommonLibConfig.java
  product-service/src/main/java/shop/genieus/product/global/config/JpaConfig.java
  product-service/src/main/java/shop/genieus/product/global/constants/Code.java
  product-service/src/main/java/shop/genieus/product/global/exception/ProductException.java
  product-service/src/main/java/shop/genieus/product/global/handler/GlobalExceptionHandler.java
  product-service/src/main/java/shop/genieus/product/infrastructure/persistence/ProductCommandAdapter.java
  product-service/src/main/java/shop/genieus/product/infrastructure/persistence/repository/ProductJpaRepository.java
  product-service/src/main/java/shop/genieus/product/presentation/rest/controller/ProductController.java
  product-service/src/main/java/shop/genieus/product/presentation/rest/dto/request/CreateProductRequest.java
  product-service/src/main/java/shop/genieus/product/presentation/rest/dto/response/CreateProductResponse.java
Labels: ❤️‍🔥 Feat

#28 [Feat] Promotion : Promotion 및 PromotionProduct 생성 로직 설계
  promotion-service/.gitignore
  promotion-service/build.gradle
  promotion-service/src/main/java/shop/genieus/promotion/PromotionServiceApplication.java
  promotion-service/src/main/java/shop/genieus/promotion/application/in/command/PromotionCommandService.java
  promotion-service/src/main/java/shop/genieus/promotion/application/in/command/dto/CreatePromotionCommand.java
  promotion-service/src/main/java/shop/genieus/promotion/application/out/client/PromotionClientPort.java
  promotion-service/src/main/java/shop/genieus/promotion/application/out/persistence/PromotionCommandPort.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/PromotionForCreate.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/PromotionProductForCreate.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/entity/BaseEntity.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/entity/Promotion.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/entity/PromotionProduct.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/vo/PromotionProductStatus.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/vo/PromotionStatus.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/vo/Rate.java
  promotion-service/src/main/java/shop/genieus/promotion/global/common/auditor/AuditorAwareImpl.java
  promotion-service/src/main/java/shop/genieus/promotion/global/config/CommonLibConfig.java
  promotion-service/src/main/java/shop/genieus/promotion/global/config/JpaConfig.java
  promotion-service/src/main/java/shop/genieus/promotion/global/constants/Code.java
  promotion-service/src/main/java/shop/genieus/promotion/global/exception/PromotionException.java
  promotion-service/src/main/java/shop/genieus/promotion/global/handler/GlobalExceptionHandler.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/client/adapter/PromotionClientAdapter.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/client/feign/ProductFeignClient.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/PromotionCommandAdapter.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/repository/PromotionJpaRepository.java
  promotion-service/src/main/java/shop/genieus/promotion/presentation/rest/controller/PromotionController.java
  promotion-service/src/main/java/shop/genieus/promotion/presentation/rest/dto/request/CreatePromotionRequest.java
  promotion-service/src/main/java/shop/genieus/promotion/presentation/rest/dto/response/CreatePromotionResponse.java
Labels: ❤️‍🔥 Feat

#34 Feat: Coupon - use coupon
  coupon-service/build.gradle
  coupon-service/src/main/java/shop/genieus/coupon/application/in/command/CouponCommandService.java
  coupon-service/src/main/java/shop/genieus/coupon/application/out/persistence/CouponCommandPort.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/entity/CouponUser.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/vo/CouponDiscountRate.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/CouponCommandAdaptor.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponJpaRepository.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponUserJpaRepository.java
  coupon-service/src/main/java/shop/genieus/coupon/presentation/rest/controller/CouponInternalController.java
Labels: 🕹️ Chore, ❤️‍🔥 Feat

#41 [Feat] Promotion: 최저가 Redis 조회 로직 추가 / 스케줄러로 Redis에 다음날 최저가 목록 갱신
  product-service/src/main/resources/sql/create_product.sql
  promotion-service/build.gradle
  promotion-service/src/main/java/shop/genieus/promotion/application/in/query/PromotionQueryService.java
  promotion-service/src/main/java/shop/genieus/promotion/application/in/query/dto/VerifyProductsRateQuery.java
  promotion-service/src/main/java/shop/genieus/promotion/application/out/persistence/PromotionProductQueryPort.java
  promotion-service/src/main/java/shop/genieus/promotion/application/out/persistence/PromotionQueryPort.java
  promotion-service/src/main/java/shop/genieus/promotion/application/system/PromotionProductService.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/entity/BaseEntity.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/vo/Product.java
  promotion-service/src/main/java/shop/genieus/promotion/global/common/auditor/AuditorAwareImpl.java
  promotion-service/src/main/java/shop/genieus/promotion/global/config/JpaConfig.java
  promotion-service/src/main/java/shop/genieus/promotion/global/config/RedisConfig.java
  promotion-service/src/main/java/shop/genieus/promotion/global/config/ScheduleConfig.java
  promotion-service/src/main/java/shop/genieus/promotion/global/config/auditor/PassportAuditorAware.java
  promotion-service/src/main/java/shop/genieus/promotion/global/constants/Code.java
  promotion-service/src/main/java/shop/genieus/promotion/global/handler/PassportRequestInterceptor.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/client/adapter/PromotionClientAdapter.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/PromotionProductQueryAdapter.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/PromotionQueryAdapter.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/repository/PromotionProductQueryRepository.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/repository/PromotionRedisHashRepository.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/scheduler/PromotionProductScheduler.java
  promotion-service/src/main/java/shop/genieus/promotion/presentation/rest/controller/PromotionInternalController.java
  promotion-service/src/main/java/shop/genieus/promotion/presentation/rest/dto/request/VerifyProductsRateRequest.java
  promotion-service/src/main/java/shop/genieus/promotion/presentation/rest/dto/response/VerifyProductsRateResponse.java
  promotion-service/src/main/resources/sql/promotion.sql
Labels: ❤️‍🔥 Feat

#42 [Feat] 주문 - 결제 통신 추가 및 커맨드 기능 리팩토링
  api-gateway/src/main/resources/local-route.yml
  order-service/build.gradle
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderCommandService.java
  order-service/src/main/java/shop/genieus/order/application/in/command/dto/CreateOrderCommand.java
  order-service/src/main/java/shop/genieus/order/application/out/client/OrderClientPort.java
  order-service/src/main/java/shop/genieus/order/domain/model/assembler/CreateOrderAssembler.java
  order-service/src/main/java/shop/genieus/order/domain/model/assembler/OrderProductAssembler.java
  order-service/src/main/java/shop/genieus/order/domain/model/entity/BaseEntity.java
  order-service/src/main/java/shop/genieus/order/domain/model/entity/Order.java
  order-service/src/main/java/shop/genieus/order/domain/model/entity/OrderProduct.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/Product.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/Promotion.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/Quantity.java
  order-service/src/main/java/shop/genieus/order/domain/service/OrderPriceCalculator.java
  order-service/src/main/java/shop/genieus/order/global/config/JpaConfig.java
  order-service/src/main/java/shop/genieus/order/global/config/PassportAuditorAware.java
  order-service/src/main/java/shop/genieus/order/global/exception/CustomServiceUnavailableException.java
  order-service/src/main/java/shop/genieus/order/global/exception/ErrorCode.java
  order-service/src/main/java/shop/genieus/order/global/handler/GlobalExceptionHandler.java
  order-service/src/main/java/shop/genieus/order/global/handler/PassportRequestInterceptor.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/OrderClientAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/OrderClientMapper.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/coupon/CouponFeignClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/coupon/CouponServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/payment/PaymentFeignClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/payment/PaymentServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/product/ProductFeignClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/product/ProductServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/promotion/PromotionFeignClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/promotion/PromotionServiceClient.java
  order-service/src/main/java/shop/genieus/order/presentation/rest/dto/request/CreateOrderRequest.java
  order-service/src/main/resources/application-local.yml
Labels: ❤️‍🔥 Feat

#37 [Feat] Payment: 결제 생성 및 결제 진행 구현
  payment-service/.gitignore
  payment-service/build.gradle
  payment-service/src/main/java/shop/genieus/payment/application/dto/CreatePaymentCommand.java
  payment-service/src/main/java/shop/genieus/payment/application/dto/ProcessPaymentCommand.java
  payment-service/src/main/java/shop/genieus/payment/application/dto/RegisterPaymentCommand.java
  payment-service/src/main/java/shop/genieus/payment/application/in/command/PaymentCommandService.java
  payment-service/src/main/java/shop/genieus/payment/application/out/persistence/PaymentCommandPort.java
  payment-service/src/main/java/shop/genieus/payment/application/out/strategy/PaymentProcessorResult.java
  payment-service/src/main/java/shop/genieus/payment/application/out/strategy/PaymentStrategy.java
  payment-service/src/main/java/shop/genieus/payment/application/out/strategy/PaymentStrategyFactory.java
  payment-service/src/main/java/shop/genieus/payment/domain/assembler/CreatePaymentAssembler.java
  payment-service/src/main/java/shop/genieus/payment/domain/model/entity/BaseEntity.java
  payment-service/src/main/java/shop/genieus/payment/domain/model/entity/Payment.java
  payment-service/src/main/java/shop/genieus/payment/domain/model/vo/Money.java
  payment-service/src/main/java/shop/genieus/payment/domain/model/vo/PaymentMethod.java
  payment-service/src/main/java/shop/genieus/payment/domain/model/vo/PaymentStatus.java
  payment-service/src/main/java/shop/genieus/payment/global/config/AuditorAwareConfig.java
  payment-service/src/main/java/shop/genieus/payment/global/config/CommonLibConfig.java
  payment-service/src/main/java/shop/genieus/payment/global/config/JpaConfig.java
  payment-service/src/main/java/shop/genieus/payment/global/config/TossMvcConfiguration.java
  payment-service/src/main/java/shop/genieus/payment/infrastructure/client/PaymentClientAdapter.java
  payment-service/src/main/java/shop/genieus/payment/infrastructure/persistence/PaymentCommandAdapter.java
  payment-service/src/main/java/shop/genieus/payment/infrastructure/processor/TossPayProcessor.java
  payment-service/src/main/java/shop/genieus/payment/infrastructure/repository/PaymentJpaRepository.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/controller/PaymentController.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/controller/PaymentInternalController.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/controller/TossWidgetController.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/dto/request/CreatePaymentRequest.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/dto/request/ProcessPaymentRequest.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/dto/request/RegisterPaymentRequest.java
  payment-service/src/main/resources/docker-database.yml
  payment-service/src/main/resources/static/style.css
  payment-service/src/main/resources/templates/checkout.html
  payment-service/src/main/resources/templates/fail.html
  payment-service/src/main/resources/templates/success.html
  payment-service/todo.md
Labels: ❤️‍🔥 Feat

#43 [Feat] 1차 MVP 테스트 후 각 서비스 수정
  coupon-service/src/main/java/shop/genieus/coupon/global/exception/GlobalExceptionHandler.java
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderCommandService.java
  order-service/src/main/java/shop/genieus/order/global/handler/GlobalExceptionHandler.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/coupon/CouponServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/payment/PaymentServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/product/ProductServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/promotion/PromotionServiceClient.java
  payment-service/build.gradle
  payment-service/src/main/java/shop/genieus/payment/global/config/AuditorAwareConfig.java
  payment-service/src/main/java/shop/genieus/payment/global/config/JpaConfig.java
  payment-service/src/main/java/shop/genieus/payment/global/config/PassportAuditorAware.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/controller/PaymentInternalController.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/dto/request/CreatePaymentRequest.java
  promotion-service/src/main/java/shop/genieus/promotion/global/handler/GlobalExceptionHandler.java
Labels: ❤️‍🔥 Feat

#46 [Feat]] 상품 재고 차감 Internal API 구현
  product-service/src/main/java/shop/genieus/product/application/in/command/ProductCommandService.java
  product-service/src/main/java/shop/genieus/product/application/in/command/dto/StockValidationResult.java
  product-service/src/main/java/shop/genieus/product/application/out/cache/ProductCachePort.java
  product-service/src/main/java/shop/genieus/product/application/out/persistence/ProductCommandPort.java
  product-service/src/main/java/shop/genieus/product/domain/model/ProductView.java
  product-service/src/main/java/shop/genieus/product/domain/model/entity/BaseEntity.java
  product-service/src/main/java/shop/genieus/product/global/config/RedisConfig.java
  product-service/src/main/java/shop/genieus/product/global/exception/InsufficientStockException.java
  product-service/src/main/java/shop/genieus/product/global/exception/ProductException.java
  product-service/src/main/java/shop/genieus/product/global/exception/ProductNotFoundException.java
  product-service/src/main/java/shop/genieus/product/global/exception/ProductUnavailableException.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/ProductCacheAdapter.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/repository/ProductRedisRepository.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/util/ProductLuaScriptProvider.java
  product-service/src/main/java/shop/genieus/product/infrastructure/persistence/ProductCommandAdapter.java
  product-service/src/main/java/shop/genieus/product/presentation/rest/controller/ProductInternalController.java
  product-service/src/main/java/shop/genieus/product/presentation/rest/mapper/ProductInternalMapper.java
  product-service/src/main/resources/redis/stock-decrease.lua
Labels: ❤️‍🔥 Feat

#47 [Feat] 주문 이벤트 구현 및 카프카,레디스 추가
  api-gateway/src/main/java/shop/genieus/gateway/config/WebClientConfig.java
  infrastructure/docker-compose.yml
  order-service/build.gradle
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderCommandService.java
  order-service/src/main/java/shop/genieus/order/application/in/event/OrderEventHandler.java
  order-service/src/main/java/shop/genieus/order/application/in/event/OrderEventPublisher.java
  order-service/src/main/java/shop/genieus/order/application/in/scheduler/OrderScheduler.java
  order-service/src/main/java/shop/genieus/order/application/out/event/OrderEventSendPort.java
  order-service/src/main/java/shop/genieus/order/application/out/persistence/OrderDelayQueuePort.java
  order-service/src/main/java/shop/genieus/order/application/out/util/OrderTimePort.java
  order-service/src/main/java/shop/genieus/order/application/policy/OrderCancelPolicy.java
  order-service/src/main/java/shop/genieus/order/application/policy/OrderDelaySchedule.java
  order-service/src/main/java/shop/genieus/order/domain/event/OrderCancelTriggerEvent.java
  order-service/src/main/java/shop/genieus/order/domain/event/OrderCreatedEvent.java
  order-service/src/main/java/shop/genieus/order/domain/service/OrderCancelPolicy.java
  order-service/src/main/java/shop/genieus/order/global/config/KafkaConsumerConfig.java
  order-service/src/main/java/shop/genieus/order/global/config/KafkaProducerConfig.java
  order-service/src/main/java/shop/genieus/order/global/config/RedisConfig.java
  order-service/src/main/java/shop/genieus/order/global/config/SchedulerConfig.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/OrderEventSendAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/producer/OrderKafkaProducer.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/queue/OrderDelayQueueAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/persistence/command/OrderCommandAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/persistence/command/repository/OrderJpaRepository.java
  order-service/src/main/java/shop/genieus/order/infrastructure/time/OrderTimeAdapter.java
  order-service/src/main/java/shop/genieus/order/presentation/event/consumer/OrderKafkaConsumer.java
  order-service/src/main/java/shop/genieus/order/presentation/event/handler/OrderKafkaEventHandler.java
  order-service/src/main/resources/application-local.yml
Labels: ❤️‍🔥 Feat

#51 [Feat] 주문 서비스 카프카 - 집킨 연동 및 공통모듈 1.5.0
  order-service/build.gradle
  order-service/src/main/java/shop/genieus/order/global/config/KafkaConsumerConfig.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/producer/OrderKafkaProducer.java
  order-service/src/main/java/shop/genieus/order/presentation/event/consumer/OrderKafkaConsumer.java
  order-service/src/main/java/shop/genieus/order/presentation/event/handler/OrderKafkaEventHandler.java
  order-service/src/main/resources/application-local.yml
Labels: ❤️‍🔥 Feat

#52 Feat: coupon 발급 로직 구현 및 배치 처리
  coupon-service/build.gradle
  coupon-service/src/main/java/shop/genieus/coupon/application/in/command/CouponCommandService.java
  coupon-service/src/main/java/shop/genieus/coupon/application/out/persistence/CouponCommandPort.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/entity/CouponUser.java
  coupon-service/src/main/java/shop/genieus/coupon/global/config/BatchJobConfig.java
  coupon-service/src/main/java/shop/genieus/coupon/global/config/RedisConfig.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/CouponCommandAdaptor.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/dto/IssueCouponCommand.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponRedisReader.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponRedisWrite.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/RedisCouponRepository.java
  coupon-service/src/main/java/shop/genieus/coupon/presentation/rest/controller/CouponController.java
  coupon-service/src/main/resources/application-batch.yml
  coupon-service/src/main/resources/redis/issue_coupon.lua
Labels: 🕹️ Chore, ❤️‍🔥 Feat, 🔥 Refactor

#55 [Chore] 모니터링을 위한 프로메테우스 설정 추가
  .gitignore
  api-gateway/build.gradle
  api-gateway/src/main/resources/application-local.yml
  auth-service/build.gradle
  auth-service/src/main/resources/application-local.yml
  coupon-service/build.gradle
  coupon-service/src/main/resources/application-local.yml
  infrastructure/docker-compose.yml
  infrastructure/prometheus.yml
  order-service/build.gradle
  order-service/src/main/resources/application-local.yml
  payment-service/build.gradle
  payment-service/src/main/resources/application-local.yml
  product-service/build.gradle
  product-service/src/main/resources/application-local.yml
  promotion-service/build.gradle
  promotion-service/src/main/resources/application-local.yml
  service-registry/src/main/resources/application-local.yml
  user-service/build.gradle
  user-service/src/main/resources/application-local.yml
Labels: 🕹️ Chore

#58 [Feat] 상품 상세 조회 기능 추가
  product-service/src/main/java/shop/genieus/product/application/in/command/dto/FindProductCommand.java
  product-service/src/main/java/shop/genieus/product/application/out/cache/ProductCachePort.java
  product-service/src/main/java/shop/genieus/product/domain/model/ProductView.java
  product-service/src/main/java/shop/genieus/product/global/constants/Code.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/ProductCacheAdapter.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/repository/ProductRedisRepository.java
  product-service/src/main/java/shop/genieus/product/presentation/rest/controller/ProductController.java
  product-service/src/main/java/shop/genieus/product/presentation/rest/dto/response/FindProductResponse.java
Labels: ❤️‍🔥 Feat

#60 [Feat] Promotion : 상품 생성 Kafka 이벤트 컨슘 처리
  promotion-service/build.gradle
  promotion-service/src/main/java/shop/genieus/promotion/application/in/command/PromotionCommandService.java
  promotion-service/src/main/java/shop/genieus/promotion/application/in/command/dto/CreatePromotionCommand.java
  promotion-service/src/main/java/shop/genieus/promotion/application/out/persistence/PromotionCommandPort.java
  promotion-service/src/main/java/shop/genieus/promotion/application/out/persistence/PromotionQueryPort.java
  promotion-service/src/main/java/shop/genieus/promotion/application/system/PromotionProductService.java
  promotion-service/src/main/java/shop/genieus/promotion/application/system/dto/UpdateProductCacheCommand.java
  promotion-service/src/main/java/shop/genieus/promotion/application/system/event/PromotionProductAddEventHandler.java
  promotion-service/src/main/java/shop/genieus/promotion/application/system/event/dto/PromotionProductAddEvent.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/constant/PromotionConstants.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/entity/PromotionProduct.java
  promotion-service/src/main/java/shop/genieus/promotion/domain/model/vo/Rate.java
  promotion-service/src/main/java/shop/genieus/promotion/global/config/AsyncConfig.java
  promotion-service/src/main/java/shop/genieus/promotion/global/config/KafkaConsumerConfig.java
  promotion-service/src/main/java/shop/genieus/promotion/global/constants/Code.java
  promotion-service/src/main/java/shop/genieus/promotion/global/handler/GlobalExceptionHandler.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/PromotionCommandAdapter.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/PromotionQueryAdapter.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/repository/PromotionJpaRepository.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/repository/PromotionRedisHashRepository.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/scheduler/PromotionProductScheduler.java
  promotion-service/src/main/java/shop/genieus/promotion/presentation/event/consumer/ProductEventHandler.java
  promotion-service/src/main/java/shop/genieus/promotion/presentation/event/consumer/ProductKafkaConsumer.java
  promotion-service/src/main/java/shop/genieus/promotion/presentation/rest/controller/PromotionAdminController.java
  promotion-service/src/main/java/shop/genieus/promotion/presentation/rest/dto/request/CreatePromotionRequest.java
  promotion-service/src/main/resources/application-local.yml
  promotion-service/src/main/resources/sql/promotion.sql
Labels: ❤️‍🔥 Feat, 🔥 Refactor

#62 [Refactor] 상품 재고 예약 기능 리팩토링
  product-service/src/main/java/shop/genieus/product/application/in/command/ProductCommandService.java
  product-service/src/main/java/shop/genieus/product/application/in/command/dto/StockValidationResult.java
  product-service/src/main/java/shop/genieus/product/application/in/query/ProductQueryService.java
  product-service/src/main/java/shop/genieus/product/application/out/cache/ProductCachePort.java
  product-service/src/main/java/shop/genieus/product/domain/model/vo/ProductStatus.java
  product-service/src/main/java/shop/genieus/product/global/exception/ProductException.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/ProductCacheAdapter.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/repository/ProductRedisRepository.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/util/ProductLuaScriptProvider.java
  product-service/src/main/java/shop/genieus/product/presentation/rest/controller/ProductInternalController.java
  product-service/src/main/java/shop/genieus/product/presentation/rest/mapper/ProductInternalMapper.java
  product-service/src/main/resources/redis/stock-decrease.lua
  product-service/src/main/resources/redis/validate-and-decrease-script.lua
Labels: ❤️‍🔥 Feat

#63 Feat: Coupon - coupon cancel
  coupon-service/build.gradle
  coupon-service/src/main/java/shop/genieus/coupon/application/in/command/CouponCommandService.java
  coupon-service/src/main/java/shop/genieus/coupon/application/out/persistence/CouponCommandPort.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/entity/CouponUser.java
  coupon-service/src/main/java/shop/genieus/coupon/global/config/KafkaConsumerConfig.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/CouponCommandAdaptor.java
  coupon-service/src/main/java/shop/genieus/coupon/presentation/event/CouponKafkaEventHandler.java
  coupon-service/src/main/java/shop/genieus/coupon/presentation/event/consumer/CouponKafkaConsumer.java
  coupon-service/src/main/resources/application-local.yml
Labels: 🕹️ Chore, ❤️‍🔥 Feat

#64 [Feat] Payment - 결제 취소, 결제 실패, 주문 취소 수신, 결제 성공 발행
  payment-service/build.gradle
  payment-service/src/main/java/shop/genieus/payment/application/in/command/OrderCommandService.java
  payment-service/src/main/java/shop/genieus/payment/application/in/command/PaymentCommandService.java
  payment-service/src/main/java/shop/genieus/payment/application/in/event/PaymentEventHandler.java
  payment-service/src/main/java/shop/genieus/payment/application/out/event/PaymentEventService.java
  payment-service/src/main/java/shop/genieus/payment/domain/event/PaymentCompleteEvent.java
  payment-service/src/main/java/shop/genieus/payment/domain/model/entity/Payment.java
  payment-service/src/main/java/shop/genieus/payment/domain/model/vo/PaymentMethod.java
  payment-service/src/main/java/shop/genieus/payment/global/config/KafkaConfig.java
  payment-service/src/main/java/shop/genieus/payment/global/exception/GlobalExceptionHandler.java
  payment-service/src/main/java/shop/genieus/payment/global/exception/PaymentErrorCode.java
  payment-service/src/main/java/shop/genieus/payment/global/exception/PaymentException.java
  payment-service/src/main/java/shop/genieus/payment/infrastructure/in/listener/KafkaPaymentListener.java
  payment-service/src/main/java/shop/genieus/payment/infrastructure/out/persistence/PaymentCommandAdapter.java
  payment-service/src/main/java/shop/genieus/payment/infrastructure/out/processor/TossPayProcessor.java
  payment-service/src/main/java/shop/genieus/payment/infrastructure/out/publisher/KafkaPaymentPublisher.java
  payment-service/src/main/java/shop/genieus/payment/infrastructure/out/repository/PaymentJpaRepository.java
  payment-service/src/main/java/shop/genieus/payment/infrastructure/persistence/PaymentCommandAdapter.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/controller/PaymentController.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/controller/PaymentInternalController.java
  payment-service/src/main/java/shop/genieus/payment/presentation/rest/dto/request/CreatePaymentRequest.java
  payment-service/src/main/resources/application-local.yml
  payment-service/src/main/resources/templates/fail.html
  payment-service/todo.md
Labels: ❤️‍🔥 Feat

#66 [Feat] 주문 취소 이벤트 컨슘 및 재고 복구 기능 구현
  product-service/.gitignore
  product-service/build.gradle
  product-service/src/main/java/shop/genieus/product/application/in/command/ProductCommandService.java
  product-service/src/main/java/shop/genieus/product/application/in/command/dto/RestoreStockCommand.java
  product-service/src/main/java/shop/genieus/product/application/out/cache/ProductCachePort.java
  product-service/src/main/java/shop/genieus/product/application/out/support/time/ProductTimePort.java
  product-service/src/main/java/shop/genieus/product/domain/model/entity/StockEvent.java
  product-service/src/main/java/shop/genieus/product/domain/model/vo/StockEventStatus.java
  product-service/src/main/java/shop/genieus/product/domain/model/vo/StockEventType.java
  product-service/src/main/java/shop/genieus/product/global/aop/KafkaTracingAspect.java
  product-service/src/main/java/shop/genieus/product/global/config/KafkaConsumerConfig.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/ProductCacheAdapter.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/repository/ProductRedisRepository.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/util/ProductLuaScriptProvider.java
  product-service/src/main/java/shop/genieus/product/infrastructure/support/time/ProductTimeAdapter.java
  product-service/src/main/java/shop/genieus/product/presentation/event/ProductKafkaConsumer.java
  product-service/src/main/java/shop/genieus/product/presentation/event/ProductKafkaEventHandler.java
  product-service/src/main/java/shop/genieus/product/presentation/event/mapper/ProductEventMapper.java
  product-service/src/main/resources/application-local.yml
  product-service/src/main/resources/redis/restore-stock-script.lua
Labels: 🕹️ Chore, ❤️‍🔥 Feat

#68 [Feat] 주문 딜레이큐 및 전체적인 구조 수정
  order-service/build.gradle
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderCommandService.java
  order-service/src/main/java/shop/genieus/order/application/in/command/dto/ExpireOrderCommand.java
  order-service/src/main/java/shop/genieus/order/application/in/event/OrderEventHandler.java
  order-service/src/main/java/shop/genieus/order/application/in/event/OrderInternalEventService.java
  order-service/src/main/java/shop/genieus/order/application/in/scheduler/OrderScheduler.java
  order-service/src/main/java/shop/genieus/order/application/in/scheduler/OrderSchedulerService.java
  order-service/src/main/java/shop/genieus/order/application/out/event/OrderEventSendPort.java
  order-service/src/main/java/shop/genieus/order/application/out/event/OrderExternalEventPort.java
  order-service/src/main/java/shop/genieus/order/application/out/event/OrderInternalEventPort.java
  order-service/src/main/java/shop/genieus/order/application/out/persistence/OrderCommandPort.java
  order-service/src/main/java/shop/genieus/order/application/out/persistence/OrderDelayQueuePort.java
  order-service/src/main/java/shop/genieus/order/application/policy/OrderCancelPolicy.java
  order-service/src/main/java/shop/genieus/order/application/policy/OrderPolicy.java
  order-service/src/main/java/shop/genieus/order/domain/event/OrderCancelTriggerEvent.java
  order-service/src/main/java/shop/genieus/order/domain/event/OrderCreatedEvent.java
  order-service/src/main/java/shop/genieus/order/domain/model/assembler/CreateOrderAssembler.java
  order-service/src/main/java/shop/genieus/order/domain/model/entity/Order.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/OrderStatus.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/OrderTimeStamp.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/Phone.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/Receiver.java
  order-service/src/main/java/shop/genieus/order/global/config/KafkaConsumerConfig.java
  order-service/src/main/java/shop/genieus/order/global/config/KafkaProducerConfig.java
  order-service/src/main/java/shop/genieus/order/global/config/PassportAuditorAware.java
  order-service/src/main/java/shop/genieus/order/global/config/RedisConfig.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/OrderEventSendAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/OrderExternalEventAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/producer/OrderKafkaProducer.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/queue/OrderDelayQueueAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/internal/OrderInternalEventAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/producer/OrderKafkaProducer.java
  order-service/src/main/java/shop/genieus/order/infrastructure/persistence/command/OrderCommandAdapter.java
  order-service/src/main/java/shop/genieus/order/presentation/event/consumer/OrderKafkaConsumer.java
  order-service/src/main/java/shop/genieus/order/presentation/event/external/OrderExternalEventHandler.java
  order-service/src/main/java/shop/genieus/order/presentation/event/external/OrderKafkaListener.java
  order-service/src/main/java/shop/genieus/order/presentation/event/handler/OrderKafkaEventHandler.java
  order-service/src/main/java/shop/genieus/order/presentation/event/internal/OrderInternalEventListener.java
  order-service/src/main/java/shop/genieus/order/presentation/rest/controller/OrderController.java
  order-service/src/main/java/shop/genieus/order/presentation/scheduler/OrderScheduler.java
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/redis/pop_expired.lua
Labels: 🕹️ Chore, ❤️‍🔥 Feat, ⚒️ Fix

#70 [Feat] Product: 주문 완료 이벤트에 컨슘 및 상품 총재고 차감 로직 구현
  product-service/.gitignore
  product-service/build.gradle
  product-service/src/main/java/shop/genieus/product/application/in/command/ProductCommandService.java
  product-service/src/main/java/shop/genieus/product/application/in/command/ProductStockCommandService.java
  product-service/src/main/java/shop/genieus/product/application/out/cache/ProductCachePort.java
  product-service/src/main/java/shop/genieus/product/application/system/dto/OrderCompletedCommand.java
  product-service/src/main/java/shop/genieus/product/global/config/KafkaConsumerConfig.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/ProductCacheAdapter.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/repository/ProductRedisRepository.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/util/ProductLuaScriptProvider.java
  product-service/src/main/java/shop/genieus/product/presentation/event/ProductKafkaConsumer.java
  product-service/src/main/java/shop/genieus/product/presentation/event/ProductKafkaEventHandler.java
  product-service/src/main/java/shop/genieus/product/presentation/event/mapper/ProductEventMapper.java
  product-service/src/main/java/shop/genieus/product/presentation/rest/controller/ProductInternalController.java
  product-service/src/main/resources/redis/order-completed.lua
  product-service/src/main/resources/redis/restore-stock-script.lua
Labels: 🕹️ Chore, ❤️‍🔥 Feat, 🔥 Refactor

#69 Feat: coupon cancel 리팩토링
  coupon-service/src/main/java/shop/genieus/coupon/application/in/command/CouponCommandService.java
  coupon-service/src/main/java/shop/genieus/coupon/application/out/persistence/CouponCommandPort.java
  coupon-service/src/main/java/shop/genieus/coupon/global/config/KafkaConsumerConfig.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/CouponCommandAdaptor.java
  coupon-service/src/main/java/shop/genieus/coupon/presentation/event/CouponKafkaEventHandler.java
Labels: 🕹️ Chore, 🔥 Refactor

#72 [Fix] 배포 전 통합테스트 후 전체 코드 수정
  api-gateway/src/main/resources/local-route.yml
  auth-service/build.gradle
  coupon-service/build.gradle
  order-service/build.gradle
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderCommandService.java
  order-service/src/main/java/shop/genieus/order/application/in/scheduler/OrderSchedulerService.java
  order-service/src/main/java/shop/genieus/order/application/policy/OrderPolicy.java
  order-service/src/main/java/shop/genieus/order/domain/event/OrderCreatedEvent.java
  order-service/src/main/java/shop/genieus/order/domain/model/entity/Order.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/OrderTimeStamp.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/queue/OrderDelayQueueAdapter.java
  payment-service/build.gradle
  product-service/build.gradle
  product-service/src/main/java/shop/genieus/product/presentation/event/ProductKafkaEventHandler.java
  product-service/src/main/java/shop/genieus/product/presentation/event/mapper/ProductEventMapper.java
  promotion-service/build.gradle
Labels: ⚒️ Fix

#73 Feature/profile setting
  .github/workflows/develop-ci-cd.yml
  .github/workflows/test-ci-cd.yml
  .gitignore
  api-gateway/Dockerfile
  api-gateway/src/main/java/shop/genieus/gateway/client/AuthServiceClient.java
  api-gateway/src/main/resources/application-dev.yml
  api-gateway/src/main/resources/application-local.yml
  api-gateway/src/main/resources/dev-route.yml
  api-gateway/src/main/resources/logback-dev.xml
  api-gateway/src/main/resources/prod-route.yml
  auth-service/Dockerfile
  auth-service/src/main/java/shop/genieus/auth/global/handler/GlobalExceptionHandler.java
  auth-service/src/main/resources/application-dev.yml
  auth-service/src/main/resources/logback-dev.xml
  coupon-service/Dockerfile
  coupon-service/src/main/resources/application-batch-dev.yml
  coupon-service/src/main/resources/application-batch.yml
  coupon-service/src/main/resources/application-dev.yml
  coupon-service/src/main/resources/logback-dev.xml
  order-service/Dockerfile
  order-service/src/main/resources/application-dev.yml
  payment-service/Dockerfile
  payment-service/src/main/resources/application-dev.yml
  product-service/Dockerfile
  product-service/src/main/resources/application-dev.yml
  promotion-service/Dockerfile
  promotion-service/src/main/resources/application-dev.yml
  service-registry/Dockerfile
  service-registry/build.gradle
  service-registry/src/main/java/shop/genieus/registry/security/SecurityConfig.java
  service-registry/src/main/resources/application-dev.yml
  service-registry/src/main/resources/application.yml
  service-registry/src/main/resources/logback-dev.xml
  user-service/Dockerfile
  user-service/src/main/resources/application-dev.yml
Labels: 🕹️ Chore, 📖 Docs, ❤️‍🔥 Feat

#74 Feat: ci-cd 워크플로우 추가
  .github/workflows/develop-ci-cd.yml
  .github/workflows/test-ci-cd.yml
  .gitignore
  api-gateway/Dockerfile
  api-gateway/src/main/java/shop/genieus/gateway/client/AuthServiceClient.java
  api-gateway/src/main/resources/application-dev.yml
  api-gateway/src/main/resources/application-local.yml
  api-gateway/src/main/resources/dev-route.yml
  api-gateway/src/main/resources/logback-dev.xml
  api-gateway/src/main/resources/prod-route.yml
  auth-service/Dockerfile
  auth-service/src/main/java/shop/genieus/auth/global/handler/GlobalExceptionHandler.java
  auth-service/src/main/resources/application-dev.yml
  auth-service/src/main/resources/logback-dev.xml
  coupon-service/Dockerfile
  coupon-service/src/main/resources/application-batch-dev.yml
  coupon-service/src/main/resources/application-batch.yml
  coupon-service/src/main/resources/application-dev.yml
  coupon-service/src/main/resources/logback-dev.xml
  order-service/Dockerfile
  order-service/src/main/resources/application-dev.yml
  payment-service/Dockerfile
  payment-service/src/main/resources/application-dev.yml
  product-service/Dockerfile
  product-service/src/main/resources/application-dev.yml
  promotion-service/Dockerfile
  promotion-service/src/main/resources/application-dev.yml
  service-registry/Dockerfile
  service-registry/build.gradle
  service-registry/src/main/java/shop/genieus/registry/security/SecurityConfig.java
  service-registry/src/main/resources/application-dev.yml
  service-registry/src/main/resources/application.yml
  service-registry/src/main/resources/logback-dev.xml
  user-service/Dockerfile
  user-service/src/main/resources/application-dev.yml
Labels: ❤️‍🔥 Feat

#75 Refactor: coupon 배치 설정 파일 추가 및 수정
  coupon-service/src/main/java/shop/genieus/coupon/CouponServiceApplication.java
  coupon-service/src/main/java/shop/genieus/coupon/application/in/command/CouponCommandService.java
  coupon-service/src/main/java/shop/genieus/coupon/domain/model/entity/CouponUser.java
  coupon-service/src/main/java/shop/genieus/coupon/global/config/BatchJobConfig.java
  coupon-service/src/main/java/shop/genieus/coupon/global/config/BatchJobRunner.java
  coupon-service/src/main/resources/application-batch-dev.yml
  coupon-service/src/main/resources/application-batch.yml
  coupon-service/src/main/resources/application-dev.yml
  coupon-service/src/main/resources/logback-dev.xml
  coupon-service/src/main/resources/redis/issue_coupon.lua
Labels: 🕹️ Chore, 🔥 Refactor

#81 Refactor: SQL 데이터 수정 및 스케줄링 시간 변경
  promotion-service/src/main/java/shop/genieus/promotion/application/system/runner/TodayLowestRateRunner.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/client/adapter/PromotionClientAdapter.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/PromotionQueryAdapter.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/persistence/repository/PromotionRedisHashRepository.java
  promotion-service/src/main/java/shop/genieus/promotion/infrastructure/scheduler/PromotionProductScheduler.java
  promotion-service/src/main/resources/sql/promotion.sql
Labels: 🕹️ Chore, 👚 Style

#87 [Refactor] Product: 상품 재고 차감 로직 수정 및 리팩토링
  product-service/src/main/java/shop/genieus/product/application/in/command/ProductStockCommandService.java
  product-service/src/main/java/shop/genieus/product/application/in/command/dto/OrderCompletedCommand.java
  product-service/src/main/java/shop/genieus/product/application/out/cache/ProductCachePort.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/ProductCacheAdapter.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/repository/ProductRedisRepository.java
  product-service/src/main/java/shop/genieus/product/presentation/event/ProductKafkaEventHandler.java
  product-service/src/main/java/shop/genieus/product/presentation/event/mapper/ProductEventMapper.java
  product-service/src/main/resources/redis/order-completed.lua
Labels: 🔥 Refactor

#88 Fix: 주문만료 및 취소 로직 수정
  order-service/src/main/java/shop/genieus/order/application/in/event/OrderInternalEventService.java
  order-service/src/main/java/shop/genieus/order/application/out/util/OrderTimePort.java
  order-service/src/main/java/shop/genieus/order/application/policy/OrderDelaySchedule.java
  order-service/src/main/java/shop/genieus/order/domain/model/vo/OrderStatus.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/producer/OrderKafkaProducer.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/queue/OrderDelayQueueAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/time/OrderTimeAdapter.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/docker-database.yml
Labels: ⚒️ Fix

#89 [Chore] 공통 라이브러리 버전 업 및 로그 설정 수정
  auth-service/build.gradle
  auth-service/src/main/resources/application-dev.yml
  coupon-service/build.gradle
  coupon-service/src/main/resources/application-dev.yml
  order-service/build.gradle
  order-service/src/main/java/shop/genieus/order/application/in/event/OrderInternalEventService.java
  order-service/src/main/java/shop/genieus/order/global/handler/GlobalExceptionHandler.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/OrderClientAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/coupon/CouponServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/payment/PaymentServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/product/ProductServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/promotion/PromotionServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/producer/OrderKafkaProducer.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/internal/OrderInternalEventAdapter.java
  order-service/src/main/java/shop/genieus/order/presentation/event/external/OrderExternalEventHandler.java
  order-service/src/main/java/shop/genieus/order/presentation/event/internal/OrderInternalEventListener.java
  order-service/src/main/java/shop/genieus/order/presentation/rest/controller/OrderController.java
  order-service/src/main/resources/application-dev.yml
  payment-service/build.gradle
  payment-service/src/main/resources/application-dev.yml
  product-service/build.gradle
  product-service/src/main/resources/application-dev.yml
  promotion-service/build.gradle
  promotion-service/src/main/resources/application-dev.yml
  user-service/build.gradle
  user-service/src/main/resources/application-dev.yml
Labels: 🕹️ Chore

#91 [Feat] 주문 서비스 메트릭 기능 추가
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderCommandService.java
  order-service/src/main/java/shop/genieus/order/presentation/event/internal/OrderInternalEventListener.java
Labels: ❤️‍🔥 Feat

#92 [Chore]: 주문 상태 변경시 배치처리 및 풀 설정
  order-service/src/main/resources/application-dev.yml
Labels: 🕹️ Chore

#95 Refactor: Coupon 리팩토링 (Bulk insert)
  coupon-service/src/main/java/shop/genieus/coupon/global/config/BatchJobConfig.java
  coupon-service/src/main/java/shop/genieus/coupon/global/config/BatchJobRunner.java
  coupon-service/src/main/java/shop/genieus/coupon/global/exception/GlobalExceptionHandler.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponRedisReader.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponRedisWrite.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponUserJpaCustom.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponUserJpaCustomImpl.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponUserJpaRepository.java
  coupon-service/src/main/resources/application-batch-local.yml
Labels: 🔥 Refactor

#96 [Refactor] Product: 중복 이밴트 검사 로직 수정
  product-service/src/main/java/shop/genieus/product/application/in/command/ProductStockCommandService.java
  product-service/src/main/java/shop/genieus/product/application/out/cache/ProductCachePort.java
  product-service/src/main/java/shop/genieus/product/application/out/support/time/ProductTimePort.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/ProductCacheAdapter.java
  product-service/src/main/java/shop/genieus/product/infrastructure/cache/repository/ProductRedisRepository.java
  product-service/src/main/java/shop/genieus/product/infrastructure/support/time/ProductTimeAdapter.java
  product-service/src/main/resources/redis/order-completed.lua
  product-service/src/main/resources/redis/restore-total-stock-script.lua
Labels: 🔥 Refactor

#98 [Feat] 상품 생성에 대한 이벤트 발행
  api-gateway/src/main/resources/application-local.yml
  api-gateway/src/main/resources/dev-route.yml
  product-service/build.gradle
  product-service/src/main/java/shop/genieus/product/application/in/command/ProductCommandService.java
  product-service/src/main/java/shop/genieus/product/application/in/event/ProductInternalEventService.java
  product-service/src/main/java/shop/genieus/product/application/out/event/internal/ProductInternalEventPort.java
  product-service/src/main/java/shop/genieus/product/application/out/event/out/ProductExternalEventPort.java
  product-service/src/main/java/shop/genieus/product/global/config/KafkaProducerConfig.java
  product-service/src/main/java/shop/genieus/product/infrastructure/event/external/ProductExternalEventAdapter.java
  product-service/src/main/java/shop/genieus/product/infrastructure/event/external/producer/ProductKafkaProducer.java
  product-service/src/main/java/shop/genieus/product/infrastructure/event/internal/ProductInternalEventAdapter.java
  product-service/src/main/java/shop/genieus/product/presentation/event/ProductInternalEventListener.java
  product-service/src/main/resources/application-local.yml
Labels: ❤️‍🔥 Feat

#99 [Fix] 주문만료 시간 설정 변경
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderCommandService.java
  order-service/src/main/java/shop/genieus/order/application/out/persistence/OrderCommandPort.java
  order-service/src/main/java/shop/genieus/order/application/policy/OrderPolicy.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/queue/OrderDelayQueueAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/persistence/command/OrderCommandAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/persistence/command/repository/OrderJpaRepository.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-local.yml
  order-service/src/main/resources/docker-database.yml
Labels: ⚒️ Fix

#104 Feat: Coupon - 쿠폰 배치 처리 시 예외처리
  coupon-service/src/main/java/shop/genieus/coupon/global/exception/GlobalExceptionHandler.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponRedisReader.java
  coupon-service/src/main/java/shop/genieus/coupon/infrastructure/persistence/repository/CouponRedisWrite.java
Labels: ❤️‍🔥 Feat

#105 [Feat] 주문 통신 수정 및 쿠폰,상품 트레이싱 로직 추가
  coupon-service/build.gradle
  coupon-service/src/main/java/shop/genieus/coupon/global/config/KafkaConsumerConfig.java
  coupon-service/src/main/java/shop/genieus/coupon/presentation/event/CouponKafkaEventHandler.java
  coupon-service/src/main/java/shop/genieus/coupon/presentation/event/consumer/CouponKafkaConsumer.java
  order-service/build.gradle
  order-service/src/main/java/shop/genieus/order/application/in/command/OrderCommandService.java
  order-service/src/main/java/shop/genieus/order/application/in/event/OrderInternalEventService.java
  order-service/src/main/java/shop/genieus/order/application/out/event/OrderExternalEventPort.java
  order-service/src/main/java/shop/genieus/order/application/out/event/OrderInternalEventPort.java
  order-service/src/main/java/shop/genieus/order/global/config/KafkaConsumerConfig.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/coupon/CouponServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/payment/PaymentServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/product/ProductServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/client/promotion/PromotionServiceClient.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/OrderExternalEventAdapter.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/external/producer/OrderKafkaProducer.java
  order-service/src/main/java/shop/genieus/order/infrastructure/event/internal/OrderInternalEventAdapter.java
  order-service/src/main/java/shop/genieus/order/presentation/event/external/OrderExternalEventHandler.java
  order-service/src/main/java/shop/genieus/order/presentation/event/internal/OrderInternalEventListener.java
  order-service/src/main/java/shop/genieus/order/presentation/rest/controller/OrderController.java
  order-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-local.yml
  product-service/build.gradle
  product-service/src/main/java/shop/genieus/product/global/config/KafkaConsumerConfig.java
  product-service/src/main/java/shop/genieus/product/presentation/event/ProductKafkaEventHandler.java
  product-service/src/main/java/shop/genieus/product/presentation/event/mapper/ProductEventMapper.java
Labels: ❤️‍🔥 Feat, ⚒️ Fix

#106 [Chore] 커넥션 풀 조정
  auth-service/src/main/resources/application-dev.yml
  coupon-service/src/main/resources/application-dev.yml
  order-service/src/main/resources/application-dev.yml
  payment-service/src/main/resources/application-dev.yml
  product-service/src/main/resources/application-dev.yml
  promotion-service/src/main/resources/application-dev.yml
Labels: 🕹️ Chore
